name: "Python Testing Pipeline"         # name of the workflow

# on -- Yeh workflow tab chalega jab koi main par push karega, 
# ya tumhara Agent koi Pull Request (PR) banayega.
on: 
  push:
    branches:
      - main
  pull_request:

# what job it will perform !!
jobs:
  test:
    runs-on: ubuntu-latest      # runner machine on which it will performs tests
    
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4   # tool to copy(clone) our whole repo in the runner machine 

      - name: "Set up Python"
        uses: actions/setup-python@v5 # python software install to run the above code 
        with:                         # with this 
          python-version: "3.10"      # this version is to installed 

      - name: "Install Dependencies"
        run: |                        # | means -- more than 1 commands to write 
          python -m pip install --upgrade pip      
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: "Run Pytest"
        run: pytest                 # in my project whole tests to run ! 

# pip install 
# pytest install to run the tests
# is requirements file exits then install all dependencies of it !! 